//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TeamControl.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TEAMCONTROL_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_REFBOXWIDGET                129
#define IDD_REMOTEROBOTWIDGET           130
#define IDD_JOYSTICKDIALOG              131
#define IDD_REALROBOTDATA               132
#define IDD_FIELDWIDGET                 133
#define IDR_TOOLBAR1                    140
#define IDD_COACHWIDGET                 150
#define IDR_MENU1                       151
#define IDD_MESSAGE_BOARD_DIALOG        152
#define IDI_DISPLAYER                   153
#define IDC_CHANGEHALF                  1000
#define IDC_CHANGELABEL                 1001
#define IDC_STOP                        1002
#define IDC_READY                       1003
#define IDC_START                       1004
#define IDC_OWNKICKOFF                  1005
#define IDC_OWNTHROWIN                  1006
#define IDC_OWNGOALKICK                 1007
#define IDC_OWNCORNERKICK               1008
#define IDC_OWNFREEKICK                 1009
#define IDC_OWNPENALTYKICK              1010
#define IDC_OPPKICKOFF                  1011
#define IDC_OPPTHROWIN                  1012
#define IDC_OPPGOALKICK                 1013
#define IDC_OPPCORNERKICK               1014
#define IDC_OPPFREEKICK                 1015
#define IDC_OPPPENALTYKICK              1016
#define IDC_OWNGOALCOLOR                1017
#define IDC_OWNLABELCOLOR               1018
#define IDC_OPPGOALCOLOR                1019
#define IDC_OPPLABELCOLOR               1020
#define IDC_CURRENTREFEREESTATE         1021
#define IDC_REFBOXCONNECT               1025
#define IDC_REFBOXIP_EDIT               1026
#define IDC_COMM_RATE_SPIN              1028
#define IDC_COMMRATE_EDIT               1029
#define IDC_PLAYER_SELECT               1030
#define IDC_ROLE_SELECT                 1031
#define IDC_REFSTATE_SELECT             1032
#define IDC_VCC_VIEW                    1033
#define IDC_NAME_EDIT                   1034
#define IDC_IP_EDIT                     1035
#define IDC_CONNECT_BUTTON              1036
#define IDC_DISCONNECT_BUTTON           1037
#define IDC_DISABLE_BUTTON              1038
#define IDC_ENABLE_BUTTON               1039
#define IDC_CHANGETEAM_BUTTON           1040
#define IDC_TEAMCOLOR_EDIT              1042
#define IDC_OWNHALF_EDIT                1043
#define IDC_VCC                         1044
#define IDC_MOTORVEL_0                  1045
#define IDC_MOTORVEL_1                  1046
#define IDC_MOTORVEL_2                  1047
#define IDC_MOTORVEL_3                  1048
#define IDC_JOYSTICK_CHECK              1049
#define IDC_MESSAGE_CHECK               1050
#define IDC_OWNS_BALL_CHECK             1051
#define IDC_COMM_BALL_CHECK             1052
#define IDC_BROADCAST_CHECK             1053
#define IDC_POLICY_COMBO                1054
#define IDC_MESSAGE_EDIT                1055
#define IDC_REFERENCE_COMBO             1056
#define IDC_DROPBALL                    1057
#define IDC_OWNSCORE                    1058
#define IDC_OPPSCORE                    1059
#define IDC_REFBOXCONNECT_CHECK         1060
#define IDC_REFBOX_IP                   1061
#define IDC_CONNECTROBOT_CHECK          1062
#define IDC_ACTIVATE_CHECK              1064
#define IDC_MSG                         1068
#define IDC_ROBOT_PLAYER_TYPE           1069
#define IDC_ROBOT_REFSTATE              1070
#define IDC_ROBOT_VELOCITY              1071
#define ID_BTN_ZOOMIN                   32778
#define ID_BTN_ZOOMOUT                  32779
#define ID_BTN_ZOOMALL                  32780
#define ID_BTN_ZOOMUNDO                 32785
#define ID_BTN_ZOOMREDO                 32786
#define ID_BTN_FILPSIDES                32787
#define ID_BTN_FILPGOALS                32788
#define ID_BTN_NEXTREFROBOT             32790
#define ID_BTN_SHOWWMROBOT              32791
#define ID_BTN_SHOWWMBALL               32792
#define ID_BTN_SHOWWMOBSTACLES          32793
#define ID_BTN_SHOWVISLINES             32794
#define ID_BTN_SHOWVISBALL              32796
#define ID_BTN_SHOWVISOBSTACLES         32797
#define ID_BTN_SHOWVISGOALS             32798
#define ID_BIN_SHOWSLPOS                32799
#define ID_BTN_SHOWAUXLINES             32800
#define ID_BTN_SHOWROBOTIDS             32801
#define ID_BTN_SHOWROBOTBALLLINKS       32802
#define ID_BTN_ROBOTTRACE               32803
#define ID_BTN_BALLTRACE                32805
#define ID_BTN_CLEARLINE                32806
#define ID_BTN_CLOCK                    32807
#define IDM_PLAYING_FIELD               32808
#define IDM_TRAINER                     32809
#define IDM_REFEREE_STATES              32810
#define IDM_JOYSTICK                    32811
#define IDM_ROBOT_DATA                  32812
#define IDM_ROBOT_REFERCE               32814
#define IDMS_ROBOT1                     32815
#define IDMS_ROBOT2                     32816
#define IDMS_ROBOT3                     32817
#define IDMS_ROBOT4                     32818
#define IDMS_ROBOT5                     32819
#define IDMS_ROBOT6                     32820
#define IDMS_ROBOT7                     32821
#define IDMS_ROBOT8                     32822
#define IDMS_ROBOT9                     32823
#define IDMS_ROBOT_SIMULATOR            32824

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
