#ifndef __HEADER_INPLAY
#define __HEADER_INPLAY

#define INPLAY_VELOCITY				1.5	
#define INPLAY_VELOCITY_NEAR_BALL	1.0	

#define MOVE2PASS_POSITION_VELOCITY 2.2
#define MOVE2BEHIND_BALL_VELOCITY	2.2	
#define MOVE2BETWEEN_BALL_VELOCITY	2.2	

//OverTime
#define POSITIONING_OVER_TIME	10
#define OPP_SETPLAY_OVER_TIME	10
#define PASS_OVER_TIME			8	

//OppKickOff
#define ALPHA_OPP_KICKOFF_BALL_DISTANCE 2100
#define BETA_OPP_KICKOFF_BALL_DISTANCE	2700

//InPlay
#define ILLEGAL_DISTANCE 4000 
#define ILLEGAL_TIME	 7.0
#define ILLEGAL_MY_MIN_DISTANCE  1600
#define ILLEGAL_OPP_MIN_DISTANCE 1400

//defence
#define DEFENCE_DISTANCE_TO_GOAL_1P		3700
#define DEFENCE_DISTANCE_TO_GOAL_2P		5000
#define DEFENCE_DISTANCE_TO_GOAL_3P		4400

//avoid
#define AVOID_DISTANCE				1500.0	
#define AVOID_DISTANCE_FOR_MY_BODY	1000.0//0.5
#define AVOID_STOP_DISTANCE			1000.0	//
#define DISTANCE_UNIT_OBSTACLES		1.0	//
#define BALL_ANGLE					0.4	//
#define BALL_DISTANCE				400	//

#define	PASS_SPEED_KICK_OFF			0.8
#define DISTANCE_TOUCH				350
#define DISTANCE_BACK				300

//Touch
#define TOUCH_VELOCITY				0.5	
#define TOUCH_BACK_DISTANCE			1000.0	
#define TIME_WAIT_UNTIL_TOUCH		2.5	
#define ALPHA_WAIT_TOUCH_DISTANCE	1.6	
#define ALPHA_WAIT_TOUCH_DISTANCE_THROW_IN	1.0
#define ALPHA_WAIT_TOUCH_DISTANCE_FOR_CORNER_KICK 0.8	
#define ALPHA_WAIT_TOUCH_VELOCITY	0.5

//MawarikomiTouch
#define MAWARIKOMI_DISTANCE_TOUCH	380
#define MAWARIKOMI_TOUCH_TIME		4.0		
#define MAWARIKOMI_ALPHA_TIME		2.0		

//Touch And Go
#define TOUCH_AND_GO_ROTATE_TIME	2.0		
#define TOUCH_AND_GO_ADJAST_TIME	2.0
#define TOUCH_AND_GO_ADJAST_TIME_CORNER	4.0

#define POSITIONING_TIME			3.0*1000.0 


#endif
