#ifndef __HEADER_POSITION
#define __HEADER_POSITION

#include "parameters.h" 

#define FIELD_HALF_LENGTH	FIELD_LENGTH/2
#define FIELD_HALF_WIDTH	FIELD_WIDTH/2
 
//Move2HomePosition 
#define VELOCITY_MOVE_TO_HOME_POSITION	1.7

#define ALPHA_HOME_POSITION_X			FIELD_HALF_LENGTH * 0.5  // -2700
#define ALPHA_HOME_POSITION_Y			FIELD_HALF_WIDTH * 0.2    // 1200
#define ALPHA_HOME_POSITION_ANGLE		0.0

#define BETA_HOME_POSITION_X			FIELD_HALF_LENGTH * -0.3  // -2700
#define BETA_HOME_POSITION_Y			FIELD_HALF_WIDTH * -0.2   // 1200
#define BETA_HOME_POSITION_ANGLE		0.0

#define GAMMA_HOME_POSITION_X			FIELD_HALF_LENGTH * -0.4  // -3600
#define GAMMA_HOME_POSITION_Y			FIELD_HALF_WIDTH * 0.0    // 0
#define GAMMA_HOME_POSITION_ANGLE		0.0

#define DELTA_HOME_POSITION_X			FIELD_HALF_LENGTH * -0.5  // -4500
#define DELTA_HOME_POSITION_Y			FIELD_HALF_WIDTH * 0.3    // 1800
#define DELTA_HOME_POSITION_ANGLE		0.0

#define EPSHILON_HOME_POSITION_X			FIELD_HALF_LENGTH * -0.5 // 4500
#define EPSHILON_HOME_POSITION_Y			FIELD_HALF_WIDTH * -0.3 // -1800
#define EPSHILON_HOME_POSITION_ANGLE		0.0

//Move2InPlayHomePostion
#define VELOCITY_MOVE_TO_INPLAY_HOME_POSITION	1.7

#define ALPHA_INPLAY_HOME_POSITION_X			FIELD_HALF_LENGTH * 0.3 // 2700
#define ALPHA_INPLAY_HOME_POSITION_Y			FIELD_HALF_WIDTH * -0.3 // -1800
#define ALPHA_INPLAY_HOME_POSITION_ANGLE		0.0

#define BETA_INPLAY_HOME_POSITION_X			FIELD_HALF_LENGTH * 0.3     // 2700
#define BETA_INPLAY_HOME_POSITION_Y			FIELD_HALF_WIDTH * 0.3      // 1800
#define BETA_INPLAY_HOME_POSITION_ANGLE		0.0

#define GAMMA_INPLAY_HOME_POSITION_X			FIELD_HALF_LENGTH * -0.2 // -1800
#define GAMMA_INPLAY_HOME_POSITION_Y			FIELD_HALF_WIDTH * 0.0   // 0
#define GAMMA_INPLAY_HOME_POSITION_ANGLE		0.0

#define DELTA_INPLAY_HOME_POSITION_X			FIELD_HALF_LENGTH * -0.5  // -4500
#define DELTA_INPLAY_HOME_POSITION_Y			FIELD_HALF_WIDTH * -0.4   // -2400
#define DELTA_INPLAY_HOME_POSITION_ANGLE		0.0

#define EPSHILON_INPLAY_HOME_POSITION_X			FIELD_HALF_LENGTH * -0.5  // -4500
#define EPSHILON_INPLAY_HOME_POSITION_Y			FIELD_HALF_WIDTH * 0.4    // 2400
#define EPSHILON_INPLAY_HOME_POSITION_ANGLE		0.0

//OppCornerKick
#define ALPHA_OPP_CORNERKICK_POSITION_X			FIELD_HALF_LENGTH * -0.85  // -7650
#define ALPHA_OPP_CORNERKICK_POSITION_Y			FIELD_HALF_WIDTH * 0.7	   // 4200	
#define ALPHA_OPP_CORNERKICK_POSITION_ANGLE		0.0	

#define BETA_OPP_CORNERKICK_POSITION_X			FIELD_HALF_LENGTH * -0.8   // -7200
#define BETA_OPP_CORNERKICK_POSITION_Y			FIELD_HALF_WIDTH * 0.5	   // 3000	
#define BETA_OPP_CORNERKICK_POSITION_ANGLE		0.0		

#define GAMMA_OPP_CORNERKICK_POSITION_X			FIELD_HALF_LENGTH * -0.7   // -6300
#define GAMMA_OPP_CORNERKICK_POSITION_Y			FIELD_HALF_WIDTH * -0.3    // -1800
#define GAMMA_OPP_CORNERKICK_POSITION_ANGLE		0.0

#define DELTA_OPP_CORNERKICK_POSITION_X			FIELD_HALF_LENGTH * -0.6   // -5400
#define DELTA_OPP_CORNERKICK_POSITION_Y			FIELD_HALF_WIDTH * 0.0	   // 0	
#define DELTA_OPP_CORNERKICK_POSITION_ANGLE		0.0

#define EPSHILON_OPP_CORNERKICK_POSITION_X		FIELD_HALF_LENGTH * -0.7   // -5400
#define EPSHILON_OPP_CORNERKICK_POSITION_Y		FIELD_HALF_WIDTH * 0.3     // 1800
#define EPSHILON_OPP_CORNERKICK_POSITION_ANGLE		0.0

#endif