/*
|==============================================================================
| Copyright (C) 2003 Prosilica.  All Rights Reserved.  Reproduction or
| disclosure of this file or its contents without the prior written consent of
| Prosilica is prohibited.
|==============================================================================
|
| File:			LogSlider.h
|
| Project/lib:	Prosilica DCAM SDK example code - viewer
|
| Target:		Win32
|
| Description:	
|
| Notes:		Originally generated by MFC app wizard.
|
|==============================================================================
| dd/mon/yy  Author		Notes
|------------------------------------------------------------------------------
| 27/Oct/03  DLee		Original.
|==============================================================================
*/

#if !defined(AFX_LOGSLIDER_H__DC030CE9_963C_4DE8_A19B_6F7FCB14ADF9__INCLUDED_)
#define AFX_LOGSLIDER_H__DC030CE9_963C_4DE8_A19B_6F7FCB14ADF9__INCLUDED_

//===== INCLUDE FILES =========================================================

//===== #DEFINES ==============================================================

//===== TYPE DEFINITIONS ======================================================

class CLogSlider : public CSliderCtrl
{
public:
	CLogSlider();
	virtual ~CLogSlider();

	int GetPos() const;
	void SetPos(int nPos);

	void GetRange(int& nMin, int& nMax) const;
	int GetRangeMin() const;
	int GetRangeMax() const;

	void SetRange(int nMin, int nMax, BOOL bRedraw = FALSE);
	void SetRangeMin(int nMin, BOOL bRedraw = FALSE);
	void SetRangeMax(int nMax, BOOL bRedraw = FALSE);

	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(CLogSlider)
	public:
	virtual BOOL Create(LPCTSTR lpszClassName, LPCTSTR lpszWindowName, DWORD dwStyle, const RECT& rect, CWnd* pParentWnd, UINT nID, CCreateContext* pContext = NULL);
	protected:
	virtual void PreSubclassWindow();
	//}}AFX_VIRTUAL

private:

	// Generated message map functions
	//{{AFX_MSG(CLogSlider)
	//}}AFX_MSG

	DECLARE_MESSAGE_MAP()

	int					m_rangeMin;
	int					m_rangeMax;

	double calcLogPos(int nPos);
};


//===== FUNCTION PROTOTYPES ===================================================

//===== DATA ==================================================================


//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LOGSLIDER_H__DC030CE9_963C_4DE8_A19B_6F7FCB14ADF9__INCLUDED_)
